----------------------------------------------------Arrays in Numpy----------------------------------------------------------

In [6]:
import numpy as np
x=[1,2,3]
y=np.array(x)
print(y)
#Just writing y will show that it is an array it is a method to chk wether its an array or not
print(type(y)) #Using type function will also tell the type of variable
print(type(x))
print(type(np))

[1 2 3]
<class 'numpy.ndarray'>
<class 'list'>
<class 'module'>


In [31]:
#Repeating the ame above program by taking user input
import numpy as np
L=[]
for i in range(1,5):
     num=int(input(f"Enter the {i} value of list: "))
     #we write int with input function bcz it gives data as string
     L.append(num)
    
print("List is",L)   

x=np.array(L)
print(f"Array is: {np.array(L)}")
print(f"Shape of array is: {x.shape}")#To see the no of rows & coloms
print(f"Dimension of array is: {x.ndim}") #To see the dimensions of array

 
 

List is [5, 5, 5, 5]
Array is: [5 5 5 5]
Shape of array is: (4,)
Dimension of array is: 1


In [29]:
#Creating a 2D array
import numpy as np
d2=np.array([[1,2,3],[4,7,8]])
print(f"2d array is \n {d2}")
print(f"type is {type(d2)}")
print(f"Shape is {d2.shape}")
print(f"Dimension of arrray is {d2.ndim}")


2d array is 
 [[1 2 3]
 [4 7 8]]
type is <class 'numpy.ndarray'>
Shape is (2, 3)
Dimension of arrray is 2


In [35]:
#3d array 
l1=[1,2,3,4]
l2=[2,1,3,4]
l3=[2,3,1,4]
d3=np.array([[l1],[l2],[l3]])
print(f"3D array is \n {d3}")
print(f"Dimension of arrray is {d3.ndim}")
print(f"type is {type(d3)}")
print(f"Shape is {d3.shape}")
#Shape will be (3,1,4) where 3 is no of rows and 4 is no of columns 



3D array is 
 [[[1 2 3 4]]

 [[2 1 3 4]]

 [[2 3 1 4]]]
Dimension of arrray is 3
type is <class 'numpy.ndarray'>
Shape is (3, 1, 4)


In [22]:

import numpy as np
x=np.arange(0,8,1)
print(x[1:3])


[1 2]


In [6]:
import numpy as np
y=np.array([[[1,2,3],[4,5,6]],[[3,5,7],[4,6,8]],[[7,7,7],[9,9,9]]])
print(y.ndim)

3


In [30]:
import numpy as np
y=np.array([[[[1,2],[1,2]]] ,[[[1,2],[1,2]]],[[[1,2],[1,2]]],[[[1,2],[1,2]]]])
print(y.ndim)

4


-----------------------------------------------Reshaping & Shape in Arrays-----------------------------------------------

In [21]:
import numpy as np
aray=np.array([[1,2,4,5],[1,2,5,6]])
print(f"Array is\n {aray}")
print(f"Shape of array is {aray.shape}") #To see the no of rows & column




Array is
 [[1 2 4 5]
 [1 2 5 6]]
Shape of array is (2, 4)


In [31]:
#Creating a Multi-Dimensional array using ndim attribute
import numpy as np
arr=np.array([0,0,0],ndmin=4)
print(f"Multidimensional array is:\n {arr}")
print(f"The shape of array is:\n {arr.shape}")
print(f"The dimension of array is: {arr.ndim}")

Multidimensional array is:
 [[[[0 0 0]]]]
The shape of array is:
 (1, 1, 1, 3)
The dimension of array is: 4


In [40]:
#Reshape 
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(f"Array before rehaping is:\n{arr}")
print(f"Dimension is: {arr.ndim}")
print(f"Shape is {arr.shape}")
re=arr.reshape(1,6)
print(f"array after reshaping\n{re}")
print(f"Dimension of array after reshaping {re.ndim}")


Array before rehaping is:
[1 2 3 4 5 6]
Dimension is: 1
Shape is (6,)
array after reshaping
[[1 2 3 4 5 6]]
Dimension of array after reshaping 2


In [53]:
#3D array by 1D array using reshape Function
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(f"Array before rehaping is:\n{arr}")
print(f"Dimension is: {arr.ndim}")
print(f"Shape is {arr.shape}")
re=arr.reshape(3,1,2)
print(f"array after reshaping into 3D: \n{re}")
print(f"Dimension of array after reshaping {re.ndim}\n")

#Recreating 1D array to 1D Array
re=arr.reshape(6,)
print(f"array after reshaping {re}")
print(f"Dimension of array after reshaping {re.ndim}")


Array before rehaping is:
[1 2 3 4 5 6]
Dimension is: 1
Shape is (6,)
array after reshaping into 3D: 
[[[1 2]]

 [[3 4]]

 [[5 6]]]

Dimension of array after reshaping 3

array after reshaping [1 2 3 4 5 6]
Dimension of array after reshaping 1


In [54]:
#3D array by 1D array using reshape Function
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(f"Array before rehaping is:\n{arr}")
print(f"Dimension is: {arr.ndim}")
print(f"Shape is {arr.shape}")
re=arr.reshape(3,1,2)
print(f"array after reshaping into 3D: \n{re}")
print(f"Dimension of array after reshaping {re.ndim}\n")

#Recreating 1D array to 1D Array
re=arr.reshape(6,)
print(f"array after reshaping {re}")
print(f"Dimension of array after reshaping {re.ndim}")
print(f"Shape of array after reshaping {re.shape}")


Array before rehaping is:
[1 2 3 4 5 6]
Dimension is: 1
Shape is (6,)
array after reshaping into 3D: 
[[[1 2]]

 [[3 4]]

 [[5 6]]]
Dimension of array after reshaping 3

array after reshaping [1 2 3 4 5 6]
Dimension of array after reshaping 1
Shape of array after reshaping (6,)


-------------------------------------------------Slicing & -ve indexing of arrays----------------------------------------

In [12]:
import numpy as np
list=[1,2,3,4,5,6,7,8,9]
a=np.array(list)
#Modifying elements using slicing
a[1:5]=0
print(a)
#print(a[0:2:1])
#print(a[-3])
#print(a[-1])
#print(a[-2])    import numpy as np
x=np.arange(10)
print(x[-1:-10:-2])


[1 0 0 0 0 6 7 8 9]
[9 7 5 3 1]


In [41]:
import numpy as np
#Slicing
a=np.array([1,2,3,4,5,6,7,9,55,33,44,56,12,347,7623,74,768,847,838,56,888,9574,2787348,552355,343433443,282227637763,8733782])
x=a[0:10] #Sart,Stop 
y=a[0:10:2] #Start, Stop , Step
z=a[5:]#Starting from 5 to end of the array
b=a[::2]#Start and stop are not specified bcz we want to add start + end value by stepping with 2
print(x)
print(y)
print(z)
#print(b,"\n\n")
#print(a)

[ 1  2  3  4  5  6  7  9 55 33]
[ 1  3  5  7 55]
[           6            7            9           55           33
           44           56           12          347         7623
           74          768          847          838           56
          888         9574      2787348       552355    343433443
 282227637763      8733782]
[        1         3         5         7        55        44        12
      7623       768       838       888   2787348 343433443   8733782] 


[           1            2            3            4            5
            6            7            9           55           33
           44           56           12          347         7623
           74          768          847          838           56
          888         9574      2787348       552355    343433443
 282227637763      8733782]


-----------------------------------------------------Slicing in 2D Array----------------------------------------------------

In [31]:
import numpy as np
a=np.array([[1,2,3,4,5],[4,5,6,8,3],[7,8,9,0,0]])
print(f"Dimension is: {a.ndim}\n")
print(a)

print(f"From 5-8:\n {a[1:2:1,-1:-5:-1]}") 
print("index of 3rd coloumn is:",a[2,0])
#Syntax
# array[row_start : row_stop : row_step,  col_start:col_stop : col_step]

#Remember in 2D Array when slicing.... in 1st part specify the indexes with comma as we know
#in 2D array row & colom index is specified... So, 1,1 means Start from the value at index 1,1

Dimension is: 2

[[1 2 3 4 5]
 [4 5 6 8 3]
 [7 8 9 0 0]]
From 5-8:
 [[3 8 6 5]]
index of 3rd coloumn is: 7


------------------------------------------Reversing Rows & Coloums of 2D Arrays--------------------------------------------

In [4]:
import numpy as np
arr=np.array([[1,2,3,4,5],[5,4,3,2,1],[6,7,8,9,10],[10,9,8,7,6]])
print(f"Array is:\n{arr}")
print(f"Array with reversed rows is:\n {arr[-1:-5:-1,::1]} ")





List1=[3,4,5] 
List2=[1,2,1] 
List3=[4,6,4]
Arr2d=np.array([[List1],[List2],[List3]])
reColom=Arr2d[:,::-1]
print("Array is:\n",reColom)   




Arr1=np.array([[3,4,5],
               [1,2,1],
               [4,6,4]])
re1=Arr1[:,::-1]
print("Array is:\n",re1)   

Array is:
[[ 1  2  3  4  5]
 [ 5  4  3  2  1]
 [ 6  7  8  9 10]
 [10  9  8  7  6]]
Array with reversed rows is:
 [[10  9  8  7  6]
 [ 6  7  8  9 10]
 [ 5  4  3  2  1]
 [ 1  2  3  4  5]] 
Array is:
 [[[3 4 5]]

 [[1 2 1]]

 [[4 6 4]]]
Array is:
 [[5 4 3]
 [1 2 1]
 [4 6 4]]


In [37]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i')

print(arr)
print(arr.dtype)


[1 2 3 4]
int32


In [58]:
import numpy as np

arr = np.array([[[1, 2, 3]], [[4, 5, 6]]])

narr = arr.reshape(-1)

print(narr) #Flatterring is converting multidimensional array into 1d array

[1 2 3 4 5 6]
