----------------------------------------------------Arrays in Numpy----------------------------------------------------------

In [ ]:
import numpy as np
x=[1.,2.,3.]
y=np.array(x)
print(y)
#Just writing y will show that it is an array it is a method to chk wether its an array or not
print(type(y)) #Using type function will also tell the type of variable
print(type(x))
print(type(np))
print(y.dtype)

In [ ]:
import numpy as np
#Ceate a numpy array using tuple and check its type and array dtype
tup=(1,2,3,4,5)
arr=np.array((tup))
print(arr)
print(f"Dimension is {arr.ndim}")

print("\n")

L=[1,2,3,4,5]
aray=np.array([L])
z=np.array(((1, 2, 3, 4),))
print(z)
print(z.ndim)
print(aray)
print(f"Dimesnsion is {aray.ndim}")

#arr3=np.array(((1,2,3)))
#print(arr3.ndim)


In [ ]:
import numpy as np
#Creating 1D array using List
aray1=np.array([1,2,3,4,5])


#Creating array using tuple
aray2=np.array((1,2,3.,4,5.))


#Checking the data-types and types  of array oject and arrays
print(type(aray1))
print(type(aray2))

print(aray1.dtype)
print(aray2.dtype)


# Creating a 2D array using List
L=[1,2,3,4,5]
aray3=np.array([L])
print(aray3)


#Creating a 2d Array using Tuple
t=((1,2,3,4,5),)
#To separate a tuple inside a tuple we hae to put comma inside it
aray4=np.array((t,))
print(aray4)


In [ ]:
import numpy as np
#Creating arrays using tuples

a=np.array((1,2,3,4,5))
b=np.array(((1,2,3,4,5),))
c=np.array(  (((1,2,3,4,5),(1,2,3,4,5)),)   )
d=np.array(    ((  ((1,2,3,4,5)  )),)   )
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


#In tuples we cannot determine the dimension by counting the number of brackets

In [ ]:
#Repeating the same above program by taking user input
import numpy as np
L=[]
for i in range(1,5):
     num=int(input(f"Enter the {i} value of list: "))
     #we write int with input function bcz it gives data as string
     L.append(num)
    
print("List is",L)   

x=np.array(L)
print(f"Array is: {np.array(L)}")
print(f"Shape of array is: {x.shape}")#To see the no of rows & coloms
print(f"Dimension of array is: {x.ndim}") #To see the dimensions of array

 
 

In [ ]:
#Creating a 2D array
import numpy as np
d2=np.array([[1,2,3],[4,7,8]])
print(f"2d array is \n {d2}")
print(f"type is {type(d2)}")
print(f"Shape is {d2.shape}")
print(f"Dimension of arrray is {d2.ndim}")


In [ ]:
#3d array 
import  numpy as np
l1=[1,2,3,4]
l2=[2,1,3,4]
l3=[2,3,1,4]
d3=np.array([[l1],[l2],[l3]])
print(f"3D array is \n {d3}")
print(f"Dimension of arrray is {d3.ndim}")
print(f"type is {type(d3)}")
print(f"Shape is {d3.shape}")
#Shape will be (3,1,4) where
#3: Represents the number of slices (or depth), so there are 3 separate 2D arrays.
#1: Represents the number of rows in each slice, so each slice contains 1 row.
#4: Represents the number of columns in each row, so each row has 4 columns.



#Example in a shape of 3D array

#(2,3,4)
#2 is the number of "slices" or depth,
#3 is the number of rows in each slice,
#4 is the number of columns in each row.



In [ ]:
import numpy as np

# Create a 1D array
array = np.arange(24)  # Array with 24 elements

# Reshape to a 3D array with shape (2, 3, 4)
reshaped_array = array.reshape((2, 3, 4))

print(reshaped_array)
print(f"Shape is {reshaped_array.shape}")


In [ ]:
import numpy as np #Reshaping 1D Array to 2D Array & 3D array
arr=np.array([1,2,3,4,5])
#print(arr.reshape(5,2))
#AS Here there are 5 elements in 1D array so when reshaping  as (5*2)!=5 so it generates error

print(arr.reshape(5,1,1))

In [ ]:
#Reshaping a 2D array in 3D array and 1D array
import numpy as np
a=np.array([[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3],[16,17,18]])
print(a.reshape(2,3,3))

#Reshaping 2D in 1D
print(f"\n{a.reshape(18,)}")


#Comma represents that it is a tuple not a single integer   :)

In [ ]:
#Reshaping a 3D array in 1D and 2D Array
import numpy as np
a=np.array([[[1,2,3,4,5]],[[1,2,3,4,5]],[[1,2,3,4,5]]])
print(a.reshape(3,5))

print("\n")

print(a.reshape(15,))

In [ ]:

import numpy as np
x=np.arange(0,8,1)
print(x[1:3])


In [ ]:
import numpy as np
y=np.array([[[1,2,3],[4,5,6]],[[3,5,7],[4,6,8]],[[7,7,7],[9,9,9]]])
print(y.ndim)

In [ ]:
import numpy as np
y=np.array([[[[1,2],[1,2]]] ,[[[1,2],[1,2]]],[[[1,2],[1,2]]],[[[1,2],[1,2]]]])
print(y.ndim)

               -----------------------------------------------Reshaping & Shape in Arrays-----------------------------------------------

In [ ]:
import numpy as np
aray=np.array([[1,2,4,5],[1,2,5,6]])
print(f"Array is\n {aray}")
print(f"Shape of array is {aray.shape}") #To see the no of rows & column




In [ ]:
#Creating a Multi-Dimensional array using ndim attribute
import numpy as np
arr=np.array([0,0,0],ndmin=4)
print(f"Multidimensional array is:\n {arr}")
print(f"The shape of array is:\n {arr.shape}")
print(f"The dimension of array is: {arr.ndim}")

In [ ]:
#Reshape 
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(f"Array before rehaping is:\n{arr}")
print(f"Dimension is: {arr.ndim}")
print(f"Shape is {arr.shape}")
re=arr.reshape(2,3)
print(f"array after reshaping\n{re}")
print(f"Dimension of array after reshaping {re.ndim}")


In [ ]:
#3D array by 1D array using reshape Function
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(f"Array before rehaping is:\n{arr}")
print(f"Dimension is: {arr.ndim}")
print(f"Shape is {arr.shape}")
re=arr.reshape(3,1,2)
print(f"array after reshaping into 3D: \n{re}")
print(f"Dimension of array after reshaping {re.ndim}\n")

#Recreating 1D array to 1D Array
re=arr.reshape(6,)
print(f"array after reshaping {re}")
print(f"Dimension of array after reshaping {re.ndim}")


In [ ]:
#3D array by 1D array using reshape Function
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(f"Array before rehaping is:\n{arr}")
print(f"Dimension is: {arr.ndim}")
print(f"Shape is {arr.shape}")
re=arr.reshape(3,1,2)
print(f"array after reshaping into 3D: \n{re}")
print(f"Dimension of array after reshaping {re.ndim}\n")

#Recreating 1D array to 1D Array
re=arr.reshape(6,)
print(f"array after reshaping {re}")
print(f"Dimension of array after reshaping {re.ndim}")
print(f"Shape of array after reshaping {re.shape}")

#reshape: Changes the shape of an existing array while keeping the number of elements constant.
#ndmin: Ensures a new array has a minimum number of dimensions, potentially adding extra dimensions if needed.




-------------------------------------------------Slicing & -ve indexing of arrays----------------------------------------

In [ ]:
import numpy as np
list=[1,2,3,4,5,6,7,8,9]
a=np.array(list)
#Modifying elements using slicing
a[1:5]=0
print(a)
#print(a[0:2:1])
#print(a[-3])
#print(a[-1])
#print(a[-2])    import numpy as np
x=np.arange(10)
print(x[-1:-10:-2])


In [ ]:
#Indexing of 1D array
import numpy as np
n=np.array([1,2,3,4,5])
print(n[0])
print(n[1])
print(n[2])
print(n[3])
print(n[4])

In [ ]:
#Indexing of 2D Array
#In a 2D array, indexing by a single index (like n[0]) returns the entire row at that index:
import numpy as np
n=np.array([[1,2,3,4,5],
            [1,2,3,4,5],
            [1,2,3,4,5],
            [1,2,3,4,5],
            [1,2,3,4,5]])

print(n[0])
print(n[1])
print(n[2])
print(n[3])
print(n[4])


print("\n To access elements of each row")
print(n[0,0])
print(n[1,0])
print(n[2,0])
print(n[3,4])
print(n[4,0])




In [ ]:
#Indexing of 3D Array
import numpy as np
n=np.array([[[1,2,3]],[[1,2,9]],[[1,2,2]]])
print(n[0,0]) #0 indx slice with 0 index row
print(n[1])
print(n[2])

print("\n")
#Here 0 is the index of 1st slice , within this slice there is only one row so this row has index 0, and foe this row the last elelment 3 has indx 2
print(n[1,0,2])

----------------------------------------------------Slicing of 1D Array---------------------------------------------------------

In [ ]:
import numpy as np
#Slicing
a=np.array([1,2,3,4,5,6,7,9,55,33,44,56,12,347,7623,74,768,847,838,56,888,9574,2787348,552355,343433443,282227637763,8733782])
x=a[0:10] #Sart,Stop 
y=a[0:10:2] #Start, Stop , Step
z=a[5:]#Starting from 5 to end of the array
b=a[::2]#Start and stop are not specified bcz we want to add start + end value by stepping with 2
print(x)
print(y)
print(z)
#print(b,"\n\n")
#print(a)

In [ ]:
import numpy as np
n=np.array([1,2,3,4,5,6,7,8,9,0,100,64,6785,765755])
#start,stop,step
y=n[1:13:1]
print(y)



-----------------------------------------------------Slicing in 2D Array----------------------------------------------------

In [ ]:
import numpy as np
a=np.array([[1,2,3,4,5],[4,5,6,8,3],[7,8,9,0,0]])
print(f"Dimension is: {a.ndim}\n")
print(a)

print(f"From 5-8:\n {a[1:2:1,-1:-5:-1]}") 
print("index of 3rd coloumn is:",a[2,0])
#Syntax
# array[row_start : row_stop : row_step,  col_start:col_stop : col_step]

#Remember in 2D Array when slicing.... in 1st part specify the indexes with comma as we know
#in 2D array row & colom index is specified... So, 1,1 means Start from the value at index 1,1

In [ ]:
#Slicing of 2D arrays
import numpy as np
x=np.array([[1,2,3,4],
            [5,6,7,81],
            [9,10,11,12]])

#Fetching the 3 elements of 1st row
y=x[0:1:1,0:3:1]
print(y)

#Fetching the elements of 3rd column
yy=x[0:3:1,3:4:1]
print(yy)





In [3]:
#Slicing of 3D Arrays
import numpy as np
c=np.array([[[1,2,3,4,5]],
            [[6,7,8,9,10]],
            [[7,8,9,5,6]]])

#Fetching the last 3 elements of 2nd slice
v=c[0:3:1,0:1:1,2:5:1]
print(v)
print(f"\n{c[2:3:1,0:1:1,2:5:1]}")

[[[ 3  4  5]]

 [[ 8  9 10]]

 [[ 9  5  6]]]

[[[9 5 6]]]


------------------------------------------Reversing Rows & Coloums of 2D Arrays--------------------------------------------

In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[5,4,3,2,1],[6,7,8,9,10],[10,9,8,7,6]])
print(f"Array is:\n{arr}")
print(f"Array with reversed rows is:\n {arr[-1:-5:-1,::1]} ")





List1=[3,4,5] 
List2=[1,2,1] 
List3=[4,6,4]
Arr2d=np.array([[List1],[List2],[List3]])
reColom=Arr2d[:,:,::-1]
print("Array is:\n",reColom)   




Arr1=np.array([[3,4,5],
               [1,2,1],
               [4,6,4]])
re1=Arr1[:,::-1]
print("Array is:\n",re1)   

In [17]:
#Reversing rows and columns in numpy array
import numpy as np
o=np.array([[33,34,35],
            [43,44,45],
            [63,64,65],
            [1,  1,  1]])
#reversing rows
r=o[-1:-5:-1,0:4:1]
print(r)

#reversing columns
rc=o[0:4:1,-1:-4:-1]
print(f"\n {rc}")


[[ 1  1  1]
 [63 64 65]
 [43 44 45]
 [33 34 35]]

 [[35 34 33]
 [45 44 43]
 [65 64 63]
 [ 1  1  1]]


In [11]:
#Reversing rows Of 3D array
import numpy as np
c=np.array([[[1,0,3,4,5],
             [5,9,3,2,1]],
            [[6,7,8,9,10],
             [10,9,8,7,6]],
            [[7,8,9,5,6],
             [6,5,9,8,7]]])

s=c[0:3:1,-1:-3:-1,0:5:1]
print(s)
print("\n")

#Reversing columns of 3D Array
s2=c[0:3:1,0:3:1,-1:-6:-1]
print(s2)


[[[ 5  9  3  2  1]
  [ 1  0  3  4  5]]

 [[10  9  8  7  6]
  [ 6  7  8  9 10]]

 [[ 6  5  9  8  7]
  [ 7  8  9  5  6]]]


[[[ 5  4  3  0  1]
  [ 1  2  3  9  5]]

 [[10  9  8  7  6]
  [ 6  7  8  9 10]]

 [[ 6  5  9  8  7]
  [ 7  8  9  5  6]]]


In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i')

print(arr)
print(arr.dtype)


[1 2 3 4]
int32


In [13]:
import numpy as np

ar=np.array([1.0,9.0,3.0,5.0],dtype='float')
print(ar)
print(ar.dtype)

[1. 9. 3. 5.]
float64


In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3]], [[4, 5, 6]]])

narr = arr.reshape(-1)

print(narr) #Flatterring is converting multidimensional array into 1d array