# Search Array
1. We can search an array for a certain value, and return the indexes that get a match.
2. To search an array, use the where() method.

In [1]:
import numpy as np
arr1=np.array([1,3,566,788,566,874636,566,4344,566,5244,343,33332,566])
        #index 0 1  2    3   4   5     6    7   8    9   10   11   12
find=np.where(arr1 == 566)
print(find)


#Searching odd numbers
arr2=np.array([1,4,6,8,10,12,14,16,18,20,21])
     #index    0 1 2 3  4  5  6  7  8  9  10
find2=np.where(arr2 % 2 !=0)
print(f"\n {find2}")

(array([ 2,  4,  6,  8, 12]),)

 (array([ 0, 10]),)


# Search Sorted Array
1. There is a method called searchsorted() which performs a binary search in the array
 and returns the index where the specified value would be inserted to maintain the search order.

In [ ]:
import numpy as np
arr1=np.array([1,5,6,7,8,9,10])

SS=np.searchsorted(arr1, 11)
print(SS)

1. Search From the Right Side
2. By default the left most index is returned
but we can give side='right' parameter to return the right most index instead.

In [15]:
import numpy as np
arr1=np.array([1,2,2,3])

SS=np.searchsorted(arr1, 2,side='right')
print(SS)

3


Working with multiple values by passing a list

In [12]:
import numpy as np
arr1=np.array([0,1,3,5,7,9])

SS=np.searchsorted(arr1,[2,4,6],side='right')
print(SS)

[2 3 4]


# Sort Array
1. Sorting is putting the data in an ordered sequence. 
2. Using the **sort()** function

In [2]:
import numpy as np
arr=np.array([10,10,9,8,5,6,7,3,4,1,2,0])

srt=np.sort(arr)
print(srt)

[ 0  1  2  3  4  5  6  7  8  9 10 10]


In [3]:
#Sorting alphabetically
import numpy as np
arr=np.array([['b','C','A','B','c','a'],['d','e','D','v','V','AB']])

srt=np.sort(arr)
print(srt)

[['A' 'B' 'C' 'a' 'b' 'c']
 ['AB' 'D' 'V' 'd' 'e' 'v']]


# Filter Array
1. Getting some elements out of an existing array and creating a new array out of them is called filtering.
2. In NumPy we filter an array using a boolean index list.

In [5]:
import numpy as np
arr=np.array(['Al Karam Studio','Maria B','Sapphire','Bareeze','Ethnic','J.'])
# Filtering in NumPy is similar to selecting only specific brands from a list of brands
# just like choosing to see dresses from only "Al Karam" and "Sapphire" on a shopping website.

fltr=[True,False,True,False,False,False]
new=arr[fltr]
print(new)
print(type(new))

['Al Karam Studio' 'Sapphire']
<class 'numpy.ndarray'>


In [6]:
import numpy as np

product = np.array([10000, 2000, 8000, 999, 5500, 4500])

# Create an empty list
f_arr = []

# go through each product
for price in product:
  if price < 5000:
    f_arr.append(True)
  else:
    f_arr.append(False)

newarr = product[f_arr]

print(f_arr)
print(newarr)

[False, True, False, True, False, True]
[2000  999 4500]
