**Numpy array can be used as matrix format and can be more than 1 diemnsional**
**but in python lists even if we add a list inside a list it is still a single list it means we cannot give it matrix format**
**Most importantly in image processing we have to work on matrices which is done using numpy array**
> **List consume large memory while array consume small memory**


In [ ]:

%timeit x=[1,2,3,4]

import numpy as np
%timeit y=np.array([1,2,3,4])

Numpy Array Creation
   
The output of list is in the form of commas 
   
The output of arrays is without commas

In [ ]:
import numpy as np
x=[1,2,3,4,5]
y=np.array(x)
print("list is",x)
print("array is",y)
print(type(x))
print(type(y))

l=[]
for i in range(1,6,1):
    user=int(input(f"Enter the {i} number: "))
    l.append(user)

arr=np.array(l)   
print(f"The array is {arr}") 
  

In [3]:
import numpy as np
List=[0,6,5,4,3]
ar=np.array(List)
print(List)
print(ar)

[0, 6, 5, 4, 3]
[0 6 5 4 3]


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[3,4,5]],ndmin=4)
print(f"2D Array is \n{arr}")
print(f"The dimension of array \n{arr} is {arr.ndim}")

d3=np.array([[[1,2,3],[1,2,3],[1,2,3]]])
print(f"\n 3D ARRAY IS \n {d3}")

#Creating Numpy Arrays using functions
1.  Zeros
2.  Ones
3.  Empty Array (The empty array stores the previous data of memory)
4.  Eye()
5.  Array with linearly spaced elements in specific interval 
   Syntax of step :   stop-start/num-1

 IMPORTANT POINTS:
> In NumPy, the default formatting for floating-point numbers often omits the trailing zero after the decimal point for simplicity and readability.

> Default Behavior in NumPy: By default, NumPy omits trailing zeros when printing floating-point numbers for simplicity. This means 3.0 might be displayed as 3. without the trailing zero.
> Control with Formatting: You can control the display of trailing zeros using formatting options in NumPy or Python’s string formatting features.

>>Consider the number 
123.4500
123.4500:

Without trailing zeros: 
123.45
123.45
With trailing zeros: 
123.4500
123.4500
Both represent the same value, but the version with trailing zeros might indicate higher precision in a scientific or engineering context.

Summary
Trailing zeros are zeros that appear after the significant digits in a number. They can convey information about precision in floating-point numbers, but do not affect the numerical value. In programming and data representation, you can control the display of trailing zeros for clarity and precision.




## Zeros

In [ ]:
#Zeros
import numpy as np
arr=np.zeros(3) #1D Array
print(arr)
print("\n \n")
arrr=np.zeros((4,8)) #2D Array
print(arrr)

we can pass teh number of rows and columns either as tuples or list... for 2D and 3D array 

but for 1D array only scalar valye is also acceptable

In [18]:
import numpy as np
a=np.zeros(3)
#a=np.zeros((3)) #Same result as above
#a=np.zeros([3]) #Same resut as above 
print(a)
print("\n")
#b=np.zeros([3,3])
b=np.zeros((3,3))
print(b)
print("\n")
c=np.zeros([3,2,5])
print(c)

[0. 0. 0.]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


## Ones 

In [21]:
#ones 
import numpy as np
np.set_printoptions(precision=1,floatmode="fixed")
arr=np.ones(5) #1D Array
print(arr)
print("\n \n")

arrr=np.ones((3,2,4)) #3D Array
print(arrr)

[1.0 1.0 1.0 1.0 1.0]

 

[[[1.0 1.0 1.0 1.0]
  [1.0 1.0 1.0 1.0]]

 [[1.0 1.0 1.0 1.0]
  [1.0 1.0 1.0 1.0]]

 [[1.0 1.0 1.0 1.0]
  [1.0 1.0 1.0 1.0]]]


In [23]:
import numpy as np
np.set_printoptions(precision=0,floatmode='fixed')
x=np.ones([2,3])
print(x)

[[1. 1. 1.]
 [1. 1. 1.]]


## Empty

In [24]:
#empty
import numpy as np
np.set_printoptions(precision=1,floatmode='fixed')
arr=np.empty(5)
print(f"{arr} \n")
arrr=np.empty((3,2,4))
print(arrr)

[1.0 1.0 1.0 1.0 1.0] 

[[[1.0 1.0 1.0 1.0]
  [1.0 1.0 1.0 1.0]]

 [[1.0 1.0 1.0 1.0]
  [1.0 1.0 1.0 1.0]]

 [[1.0 1.0 1.0 1.0]
  [1.0 1.0 1.0 1.0]]]


## Eye

> The np.eye() function in NumPy creates a 2D identity matrix. However, it does not directly support creating a 3D identity matrix.

> If you need a 3D array with identity-like properties, you would have to construct it manually

>N is the number of rows.

>M is the number of columns.

>k is the diagonal offset, where:

>k=0 is the main diagonal.

>k>0 is above the main diagonal.

>k<0 is below the main diagonal.

In [32]:
#eye()
import numpy as np
np.set_printoptions(precision=0, floatmode='fixed')
arr=np.eye(3)
print(arr)
print("\n \n")

arrr=np.eye(3,2,3)
print(arrr)




#numpy.ones(): Creates an array filled entirely with ones. It does not create an identity matrix.
#numpy.eye(): Creates a 2-D array with ones on the diagonal and zeros elsewhere, which is an identity matrix if 
# the array is square.

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 

[[0. 0.]
 [0. 0.]
 [0. 0.]]


## Linspace

In [ ]:
#Linspace
import numpy as np
a=np.linspace(1,10,num=5)
print(a)

## Random Arrays
 All these are the part of random library so they should be called with random.rand() ...
1. rand()   generate random value b/w 0,1
2. randn()  generate random value close to 0 can also contain -ve values can also contain values like 1.000 mean 1 can be included

rand() and ranf() almost same  

3. ranf()   generate the floating random numbers from 0.0 - 1.0 but not 1 itself 
4. randint() generates random numbers in given range

# rand()

In [ ]:
import numpy as np
n=np.random.rand(4)
print(n)

# randn()

In [ ]:
import numpy as np
n=np.random.randn(5)
print(n)

# ranf()

In [ ]:
import numpy as np
n=np.random.ranf(6)
print(n)


# randint()

In [ ]:
import numpy as np
x=np.random.randint(3,10,6)  #(min,max,total)
print(x)

# Data Type

Points to remember

Use type() to determine the type of the entire object.

Use dtype to determine the data type of the elements within a NumPy array.

# Type promotion in Numpy

When you try to create a NumPy array with mixed data types, NumPy automatically promotes the data types to a common type that can represent all the elements. This process is known as type promotion.

In [ ]:
import numpy as np
x=np.arange(0,11,1,dtype="f") #Here instead of writing np.float we simply wrote "f" for float data type
print(f"Array is \n {x}")
print(f"\n Data type of array is: {x.dtype}")  #dtype is an attribute

s=np.array(['s','t','r','i','n','g'])
print(f"\n Data type of array is: {s.dtype}")



#Remember taht we use type to check that wether its array or list or tuple e.t.c
# But we use dtype to check the data type of the array

Converting the data type of an array without dtype attribute just by using function as follow:

In [ ]:
import numpy as np
x=np.array([1,2,3,4,5])
new=np.float32(x)    # Here array is passed as an argument
print(f"Array is \n {x}")
print(f"Converted array is: {new}")
print(f"{new}: {new.dtype}")
print(f"{x}: {x.dtype}")



# astype Function

Yes, the astype method in NumPy is used to explicitly convert the data type of an array.

 This is useful when you want to change the data type of an array to a specific type.

In [ ]:
import numpy as np
x=np.array([1,2,3,4,5])
new=x.astype(float)   #Here data type is passed as an argument

print(x)
print("\n \n")
print(new)


In [ ]:
import numpy as np
n=np.array([1,2,5.6,'a'])
print(f"\n {n}")
#print(f"\n {n[1:0:-1,0:3:1]}")


