Numpy array can be used as matrix format and can be more than 1 diemnsional

but in python lists enev if we add a list inside a list it is still a single list
 it means we cannot give it matrix format

Most importantly in image processing we have to woek on matrices which is done using numpy array
List consume large memory while array consume small memory


In [ ]:

%timeit x=[1,2,3,4]

import numpy as np
%timeit y=np.array([1,2,3,4])

-Numpy Array Creation
   
   The output of list is in the form of commas 
   
   The output of arrays is without commas

In [ ]:
import numpy as np
x=[1,2,3,4,5]
y=np.array(x)
print("list is",x)
print("array is",y)
print(type(x))
print(type(y))

l=[]
for i in range(1,6,1):
    user=int(input(f"Enter the {i} number: "))
    l.append(user)

arr=np.array(l)   
print(f"The array is {arr}") 
  

In [ ]:
import numpy as np
arr=np.array([[1,2,3],[3,4,5]],ndmin=4)
print(f"2D Array is \n{arr}")
print(f"The dimension of array \n{arr} is {arr.ndim}")

d3=np.array([[[1,2,3],[1,2,3],[1,2,3]]])
print(f"\n 3D ARRAY IS \n {d3}")

#Creating Numpy Arrays using functions
1.  Zeros
2.  Ones
3.  Empty Array (The empty array stores the previous data of memory)
4.  Eye()
5.  Array with linearly spaced elements in specific interval 
   Syntax of step :   stop-start/num-1

 IMPORTANT POINTS:
> In NumPy, the default formatting for floating-point numbers often omits the trailing zero after the decimal point for simplicity and readability.

> Default Behavior in NumPy: By default, NumPy omits trailing zeros when printing floating-point numbers for simplicity. This means 3.0 might be displayed as 3. without the trailing zero.
> Control with Formatting: You can control the display of trailing zeros using formatting options in NumPy or Python’s string formatting features.

>>Consider the number 
123.4500
123.4500:

Without trailing zeros: 
123.45
123.45
With trailing zeros: 
123.4500
123.4500
Both represent the same value, but the version with trailing zeros might indicate higher precision in a scientific or engineering context.

Summary
Trailing zeros are zeros that appear after the significant digits in a number. They can convey information about precision in floating-point numbers, but do not affect the numerical value. In programming and data representation, you can control the display of trailing zeros for clarity and precision.




## Zeros

In [ ]:
#Zeros
import numpy as np
arr=np.zeros(3) #1D Array
print(arr)
print("\n \n")
arrr=np.zeros((4,8)) #2D Array
print(arrr)

## Ones 

In [ ]:
#ones 
import numpy as np
np.set_printoptions(precision=1,floatmode="fixed")
arr=np.ones(5) #1D Array
print(arr)
print("\n \n")

arrr=np.ones((3,2,4)) #3D Array
print(arrr)

## Empty

In [ ]:
#empty
import numpy as np
np.set_printoptions(precision=1,floatmode='fixed')
arr=np.empty(5)
print(f"{arr} \n")
arrr=np.empty((3,2,4))
print(arrr)

## Eye

In [5]:
#eye()
import numpy as np
np.set_printoptions(precision=0, floatmode='fixed')
arr=np.eye(3)
print(arr)
print("\n \n")

arrr=np.eye(3,5)
print(arrr)




#numpy.ones(): Creates an array filled entirely with ones. It does not create an identity matrix.
#numpy.eye(): Creates a 2-D array with ones on the diagonal and zeros elsewhere, which is an identity matrix if 
# the array is square.

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# identity()
1. numpy.identity(n) always creates an n x n square identity matrix.
2. So we cannot specify the no of coloms like (3,4) it will generate error

**Similarities:**
1. Both numpy.eye and numpy.identity generate 2D matrices with 1's on the diagonal.
2. Both numpy.eye and numpy.identity are used to generate identity matrices.

**Differences:**
1. numpy.identity(n) always generates a square matrix of size n x n.
2. numpy.eye(N, M) can generate a matrix of any order, not necessarily square.
3. You can specify the number of rows (N) and columns (M).

In [4]:
import numpy as np
arr=np.identity(3)
print(arr)
print("\n \n")

arrr=np.identity(5)
print(arrr)




[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Linspace

In [1]:
#Linspace
import numpy as np
a=np.linspace(1,10,num=5)
print(a)

[ 1.    3.25  5.5   7.75 10.  ]


## Random Arrays
 All these are the part of random library so they should be called with random.rand() ...
1. rand()   generate random value b/w 0,1
2. randn()  generate random value close to 0 can also contain -ve values can also contain values like 1.000 mean 1 can be included

rand() and ranf() almost same  

3. ranf()   generate the floating random numbers from 0.0 - 1.0 but not 1 itself 
4. randint() generates random numbers in given range

# rand()

In [46]:
import numpy as np
n=np.random.rand(4)
print(n)

[0.48004738 0.88890521 0.59134908 0.96280535]


# randn()

In [4]:
import numpy as np
n=np.random.randn(5)
print(n)

[-0.35135669  1.94772514 -1.68130926  1.06656499 -0.34101453]


# ranf()

In [49]:
import numpy as np
n=np.random.ranf(6)
print(n)


[0.7683695  0.43753169 0.25152134 0.35901478 0.51959415 0.13520307]


# randint()

In [56]:
import numpy as np
x=np.random.randint(3,10,6)  #(min,max,total)
print(x)

[6 6 4 7 7 8]


# Data Type

Points to remember

Use type() to determine the type of the entire object.

Use dtype to determine the data type of the elements within a NumPy array.

# Type promotion in Numpy

When you try to create a NumPy array with mixed data types, NumPy automatically promotes the data types to a common type that can represent all the elements. This process is known as type promotion.

In [64]:
import numpy as np
x=np.arange(0,11,1,dtype="f") #Here instead of writing np.float we simply wrote "f" for float data type
print(f"Array is \n {x}")
print(f"\n Data type of array is: {x.dtype}")  #dtype is an attribute

s=np.array(['s','t','r','i','n','g'])
print(f"\n Data type of array is: {s.dtype}")



#Remember taht we use type to check that wether its array or list or tuple e.t.c
# But we use dtype to check the data type of the array

Array is 
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

 Data type of array is: float32

 Data type of array is: <U1


Converting the data type of an array without dtype attribute just by using function as follow:

In [66]:
import numpy as np
x=np.array([1,2,3,4,5])
new=np.float32(x)    # Here array is passed as an argument
print(f"Array is \n {x}")
print(f"Converted array is: {new}")
print(f"{new}: {new.dtype}")
print(f"{x}: {x.dtype}")


Array is 
 [1 2 3 4 5]
Converted array is: [1. 2. 3. 4. 5.]
[1. 2. 3. 4. 5.]: float32
[1 2 3 4 5]: int64


# astype Function

Yes, the astype method in NumPy is used to explicitly convert the data type of an array.

 This is useful when you want to change the data type of an array to a specific type.

In [67]:
import numpy as np
x=np.array([1,2,3,4,5])
new=x.astype(float)   #Here data type is passed as an argument

print(x)
print("\n \n")
print(new)


[1 2 3 4 5]

 

[1. 2. 3. 4. 5.]
