# Indexing of 1D Array
Remember while catching the element in 1D array through index this is indexing and contain one value only no loop such as below example

a[1] or a[2] e.t.c  or a[-1] to get elemnt in reverse

There is only one value of index in indexing also there is no start, stop, step


In [7]:
import numpy as np
x=np.arange(1,6,1)
print(f"With +ve indexing the array is {x}")
print(x[2])

#Remember while catching the element in 1D array through index this is indexing and contain one value only no loop such as above example

With +ve indexing the array is [1 2 3 4 5]
3


# Indexing of 2D Array

In 2D Array's Indexing there is indexing but no start stop step 

1st index is for row and 2nd index is for coloum

Example: x[0,1]  

# In slicing there is [1:1]  Colon b/w row and column while in Indexing there is [1,2] comma

In [2]:
import numpy as np
x=np.array([[9,8,7],[1,2,3]])
print(x)
print(x[0,0])
print(x[0,1])
print(x[0,2])
print(x[1,0])
print(x[1,1])
print(x[1,2])

[[9 8 7]
 [1 2 3]]
9
8
7
1
2
3


# Indexing of 3D Array


In [2]:
import numpy as np
x=np.array([  [[1,2,3],
              [4,5,6],
              [9,67,45]] ])
print(x)

print(x[0,2,1])

[[[ 1  2  3]
  [ 4  5  6]
  [ 9 67 45]]]
67


In [4]:
import numpy as np
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
x2=x[1:11:2]
print(x2)

[ 2  4  6  8 10]


In [5]:
import numpy as np
x=np.array([[1,2,3,4,5],
            [6,7,8,9,10],
            [11,12,13,14,15]])
x2=x[2:3:1,1:4:1]
print(x2)

[[12 13 14]]


In [16]:
import numpy as np
x=np.array([[[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15]]])
x2=x[0:3:1,0:4:1,1:4:1]
print(x2)

[[[ 2  3  4]
  [ 7  8  9]
  [12 13 14]]]
