Ways to create 1D Array
1:Creating Numpy array Using List
2:Initialize a Python NumPy Array Using Special Functions

In [1]:
import numpy as np
ZeroArr=np.zeros((3,2))
OneArr=np.ones((5,3))
constArr=np.full((2,3),8)
rangeArr=np.arange(0,10,1)# start, stop, step
lineArr=np.linspace(0,1,5)# start, stop, num

print(ZeroArr)
print(OneArr)
print(constArr)
print(rangeArr)
print(lineArr)


[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[8 8 8]
 [8 8 8]]
[0 1 2 3 4 5 6 7 8 9]
[0.   0.25 0.5  0.75 1.  ]


In [ ]:
import numpy as np
List=[1,4,6,7,8]
arr=np.array(List)
print("1D Array using list is: ", arr)

1D Array using list is:  [1 4 6 7 8]


In [1]:
import numpy as np
x =[1, 2, 3, 4]
y = np.array(x) 
print(y) 

[1 2 3 4]


In [5]:
import numpy as np
a=np.arange(2,3,.5)
print(a)
x=x=np.dtype('i4')
print(x)

[2.  2.5]
int32


In [2]:
import numpy as np
a=np.array([4,6,7],dtype=float)
a[::1]
print(a)

[4. 6. 7.]


In [18]:
import numpy as np
x=np.array([[1,2,3,4,5],[1,2,3,4,5]])
#print(x)
v=x.copy()
v.view()
v[0:2]=1
print(v)

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [21]:
import numpy as np
a=np.identity(2)
print(a)

[[1. 0.]
 [0. 1.]]


In [22]:
import numpy as np
a=np.array([1,2,3,4,5])
sp=np.array_split(a,3)
print(type(sp))

<class 'list'>


In [23]:
a=np.array([1,2,3])
b=np.array([1,2,3,4])
print(a+b)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [34]:
import numpy as np
x=np.array(['a','b'])
a=x.dtype
print(a)

<U1


In [35]:
import numpy as np
a=np.arange(5)
b=np.arange(len(a),len(a)+len(a))
print(b)

[5 6 7 8 9]


In [36]:
import  numpy as np
v=np.array([1,2])
for i in v:
    print(v[i])
 
    

2


IndexError: index 2 is out of bounds for axis 0 with size 2

In [37]:
import numpy as np
a=np.array([1,2,3,4])
for i in range(len(a)):
    print(i)
    

0
1
2
3
