# Copy vs view

Changing copy array will not affect the original array:

In [2]:
import numpy as np
org=np.array([1,2,3,4])
co=org.copy()
print(f"original array is {org}")
print(f"Copy array is {co}")
co[0:4:1]=[6,7,8,9]
print(f"Copy array after change is {co}")
print(f"original array after change in copy is {org}")


original array is [1 2 3 4]
Copy array is [1 2 3 4]
Copy array after change is [6 7 8 9]
original array after change in copy is [1 2 3 4]


Changing Original Array will not affect the copy array


In [3]:
import numpy as np
org=np.array([1,2,3,4,5])
co=org.copy()
print(f"original array is {org}")
print(f"Copy array is {co}")
org[0:4:1]=[6,7,8,9]
print(f"Original array after change is {org}")
print(f"copy array after change in original is {co}")


original array is [1 2 3 4 5]
Copy array is [1 2 3 4 5]
Original array after change is [6 7 8 9 5]
copy array after change in original is [1 2 3 4 5]


Changing the view will affect the original array

In [4]:
import numpy as np
org=np.array([0,7,8,9,5,99,100,400,500])
vi=org.view()
print(f"Original array is{org}")
print(f"The View array is {vi}")
vi[1:len(org):1]=[1,1,2,3,5,8,13,21]
print(f"View array after change is {vi}")
print(f"Original array after change in view is {org}")


Original array is[  0   7   8   9   5  99 100 400 500]
The View array is [  0   7   8   9   5  99 100 400 500]
View array after change is [ 0  1  1  2  3  5  8 13 21]
Original array after change in view is [ 0  1  1  2  3  5  8 13 21]


Changing Original array will affect the view

In [5]:
import numpy as np
org=np.array([0,7,8,9,5,99,100,400,500])
vi=org.view()
print(f"Original array is{org}")
print(f"The View array is {vi}")
org[1:len(org):1]=[22,22,22,22,22,22,22,22]
print(f"Original array after change is {org}")
print(f"View array after change in Original is {vi}")


Original array is[  0   7   8   9   5  99 100 400 500]
The View array is [  0   7   8   9   5  99 100 400 500]
Original array after change is [ 0 22 22 22 22 22 22 22 22]
View array after change in Original is [ 0 22 22 22 22 22 22 22 22]


# Joining Numpy Arrays:
Using Concatenate Function:

Joining means putting contents of two or more arrays in a single array.

 We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.


In [11]:
import numpy as np
#arr1 = np.array([[1, 2], [3, 4]])
#arr2 = np.array([[5, 6], [7, 8]])
arr1 = np.array([5, 6, 8])
arr2 = np.array([5, 7, 8])
arr = np.concatenate((arr1, arr2),axis=0)
print(arr)


[5 6 8 5 7 8]


# stack()

Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
We pass a sequence of arrays that we want to join to the stack() method along with the axis.
 If  axis is not explicitly passed it is taken as 0.


In [7]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)


[[1 4]
 [2 5]
 [3 6]]


# hstack()

In [10]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)



[1 2 3 4 5 6]


# vstack()

In [7]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)


[[1 2 3]
 [4 5 6]]


# dstack()

In [1]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)


[[[1 4]
  [2 5]
  [3 6]]]


# Split
> Splitting breaks one array into multiple.
> We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [28]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,1,1,1])
sp=np.array_split(arr,3)
print(sp)
print("\n Splitted arrays accessing ")
#Accessing the splitted arrays
print(sp[0])
print(sp[1])
print(sp[2])
print("\n")

#Splitting 2D Arrays

arr2 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr2, 5)
print(newarr)
print("\n")
print(newarr[3])
print("\n")

#Splitting along axis either horizontally or vertiaclly
h=np.hsplit(arr,2)
print(h)

v=np.array_split(arr2,5,axis=1)
print(v)
#Similar alternates to vstack() and dstack() are available as vsplit() and dsplit().


[array([1, 2, 3, 4]), array([5, 6, 7]), array([1, 1, 1])]

 Splitted arrays accessing 
[1 2 3 4]
[5 6 7]
[1 1 1]


[array([[1, 2],
       [3, 4]]), array([[5, 6]]), array([[7, 8]]), array([[ 9, 10]]), array([[11, 12]])]


[[ 9 10]]


[array([1, 2, 3, 4, 5]), array([6, 7, 1, 1, 1])]
[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int64), array([], shape=(6, 0), dtype=int64), array([], shape=(6, 0), dtype=int64)]
