In [4]:
import numpy as np

# Creating a 1D array 

arr = np.arange(10)
print("1D Array is:", arr) 
# Extracting odds from the array
odds = arr[arr % 2 != 0]
print("Odd numbers are:", odds)

# Replacing odds with -1
arr[arr % 2 != 0] = -1                                                        
print("Replaced array with -1:", arr)

# Creating a 2D array
new2Darr = arr.reshape(2, 5) #-1 indicates total no of elements remain unchanged
"""Reshape to 2D array: The method call arr.reshape(2, -1) is asking NumPy to reshape the array into 2 rows. 
The -1 tells NumPy to automatically calculate the number of columns that will be needed to fit all the elements.

The original array has 10 elements.
When reshaping to 2 rows, each row will need to have 10 / 2 = 5 columns.
So, arr.reshape(2, -1) results in a 2x5 array.
"""
print("Converted 1D to 2D Array is:\n", new2Darr)

# Creating lists
List1 = [1, 3, 5]
List2 = [4, 6, 7]
List3 = [66, 77, 88]
List4 = [33, 79, 100]

# Creating 2D arrays
x = np.array([List1, List2])
y = np.array([List3, List4])

# Stacking arrays vertically and horizontally
vertical = np.vstack((x, y))
horizontal = np.hstack((x, y))

print("Vertically stacked arrays are:\n", vertical)
print("Horizontally stacked arrays are:\n", horizontal)




1D Array is: [0 1 2 3 4 5 6 7 8 9]
Odd numbers are: [1 3 5 7 9]
Replaced array with -1: [ 0 -1  2 -1  4 -1  6 -1  8 -1]
Converted 1D to 2D Array is:
 [[ 0 -1  2 -1  4]
 [-1  6 -1  8 -1]]
Vertically stacked arrays are:
 [[  1   3   5]
 [  4   6   7]
 [ 66  77  88]
 [ 33  79 100]]
Horizontally stacked arrays are:
 [[  1   3   5  66  77  88]
 [  4   6   7  33  79 100]]


Part#2

In [24]:
import numpy as np

arr1=np.array([1,2,3,4,5])
arr2=np.array([2,3,4,5,6])

common=np.intersect1d(arr1,arr2)
print("Intersection of array 1 and array 2 is",common)

#From array a remove all items present in array b
diff=np.setdiff1d(arr1,arr2)
print("Difference of array 1 and array 2 is",diff)

#Reverse the columns of a 2D array arr
Arr2d=np.array([[3,4,5],[1,2,1],[4,6,4]])
reColom=Arr2d[:,::-1]
print("2D array with reversed coloums is:\n",reColom)

randarr = np.random.uniform(5, 10, (5, 3))
print("2D array with random decimal numbers between 5 and 10 are : ", randarr)

#  Create a 5x5 matrix with values 1, 2, 3, 4 just below the diagonal
matrix = np.diag(np.arange(1,5,1), k=-1)
print("5x5 matrix with values 1, 2, 3, 4 just below the diagonal:\n", matrix)




Intersection of array 1 and array 2 is [2 3 4 5]
Difference of array 1 and array 2 is [1]
2D array with reversed coloums is:
 [[5 4 3]
 [1 2 1]
 [4 6 4]]
2D array with random decimal numbers between 5 and 10 are :  [[7.66208539 7.29043815 7.11074849]
 [5.64104147 5.9440869  9.95704072]
 [8.47774492 5.81456166 7.51547818]
 [5.28897306 7.76250391 6.48687814]
 [6.95529722 9.22760694 9.457577  ]]
5x5 matrix with values 1, 2, 3, 4 just below the diagonal:
 [[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Part 3

In [25]:
import numpy as np

# Input array
a = np.array([1, 2, 3])

# Tile the array 'a' three times
rep=np.repeat(a,3)
output = np.tile(a, 3)

print("Output pattern:")
print(rep,output)


"""Tiling is a concept in mathematics and computer science, particularly in the context
of arrays and matrices. In mathematics, tiling refers to covering a plane with one or more geometric 
shapes without any gaps or overlaps. Similarly, in NumPy (and other programming contexts), tiling refers to the 
process of repeating an array along specified dimensions to create a larger array."""

Output pattern:
[1 1 1 2 2 2 3 3 3] [1 2 3 1 2 3 1 2 3]


'Tiling is a concept in mathematics and computer science, particularly in the context\nof arrays and matrices. In mathematics, tiling refers to covering a plane with one or more geometric \nshapes without any gaps or overlaps. Similarly, in NumPy (and other programming contexts), tiling refers to the \nprocess of repeating an array along specified dimensions to create a larger array.'