# Universal Functions
1. NumPy functions that operate on the ndarray object
2. ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.
3. **Vectorization** allows more efficient and readable numerical computations by applying operations to entire arrays or matrices at once.

# add()

In [2]:
import numpy as np

arr1 = [1, 2, 3, 4]
arr2 = [4, 5, 6, 7]
sum = np.add(arr1,arr2)  #makes the code shorter and faster 

print(sum)
print(type(np.add))

[ 5  7  9 11]
<class 'numpy.ufunc'>


Creating our own ufunc

In [9]:
import numpy as np
def addition(L1,L2,L3):
    return L1+L2+L3

addition=np.frompyfunc(addition,3,1) #(function_name, input_count, output_count)
#function_name: The Python function you want to convert into a ufunc.
#input_count: The number of input arguments the function takes
#output_count: The number of outputs the function returns.



L1=[1,2,3]
L2=[4,5,6]
L3=[1,0,0]
result=addition(L1,L2,L3)
print(result)
print(f"Type is {type(addition)}")

[6 7 9]
Type is <class 'numpy.ufunc'>


# Simple Airthemetic
1. Addition
2. Subtraction
3. Multiplication
4. Division
1. Arithmetic Conditionally: means that we can define conditions where the arithmetic operation should happen

In [6]:
#We have already seen add() function
import numpy as np
L1=[1,2,3]
L2=[4,5,6]
arr1 = np.array(L1)
arr2 = np.array(L2)

arr3 = np.subtract(arr1, arr2)

print(arr3)

[-3 -3 -3]


In [7]:
#multiply()
import numpy as np
L1=[1,2,3]
L2=[4,5,6]
arr1 = np.array(L1)
arr2 = np.array(L2)

arr3= np.multiply(arr1, arr2)

print(arr3)

[ 4 10 18]


In [12]:
#divide
import numpy as np
L1=[4,100,18]
L2=[4,10,6]
arr1 = np.array(L1)
arr2 = np.array(L2)

arr3= np.divide(arr1, arr2)

print(arr3)

[ 1. 10.  3.]


In [1]:
#Power()
#Raise the valules in arr1 to the power of values in arr2:
import numpy as np
L1=[2,4,7]
L2=[2,2,2]
arr1 = np.array(L1)
arr2 = np.array(L2)

arr3= np.power(arr1, arr2)

print(arr3)

[ 4 16 49]


In [2]:
#mod() or Remainder
import numpy as np
L1=[2,4,7,10,100,24,22]
L2=[2,2,2,2,2,4,11]
arr1 = np.array(L1)
arr2 = np.array(L2)

arr3= np.mod(arr1, arr2) #mod() also gives same result

print(arr3)

[0 0 1 0 0 0 0]


In [17]:
#The divmod() function returns both the quotient and the the mod. 
import numpy as np
L1=[2,4,7,10,100,24,22]
L2=[2,2,2,2,2,4,11]
arr1 = np.array(L1)
arr2 = np.array(L2)

arr3= np.divmod(arr1, arr2) 

print(arr3)

(array([ 1,  2,  3,  5, 50,  6,  2]), array([0, 0, 1, 0, 0, 0, 0]))


Absolute values
1. The absolute value of a number x is denoted as ∣x∣.
2. It represents the distance of x from zero on the number line, regardless of direction.
3. The absolute value of a number is always non-negative (0 or positive).
4.  Example: ∣−3∣ = 3


In [3]:
#Absolute Values
import numpy as np

aray = np.array([-1000, -20, 21, 72, 93, -84])

newaray = np.absolute(aray)

print(newaray)


[1000   20   21   72   93   84]


# Summuation
1. Addition is done between two arguments whereas summation happens over n elements


In [4]:
import numpy as np
L1=[30,30,30]
L2=[10,10,10]
arr1 = np.array(L1)
arr2 = np.array(L2)
arr3= np.sum([arr1, arr2],axis=0)  #sum can be done along axis too

print(arr3)
#commulative sum (partially adding the elements in array)
aray=np.array([1,2,2,4])  # 1   1+2   1+2+2   1+2+2+4
csum=np.cumsum(aray)
print(csum)



[40 40 40]
[1 3 5 9]


# LCM

In [12]:


#num1 = 5 
#num2 = 6
#LCM = np.lcm(num1, num2)
#print(LCM)
#LCM of array
import numpy as np
arr = np.array([4, 14, 2])

result= np.lcm.reduce(arr)

print(result)
print(result.ndim)
print(arr.ndim)


28
0
1


# Trigonometric Functions
1. the ufuncs sin(), cos() and tan() that take values in radians and produce the corresponding sin, 
    cos and tan values.

In [3]:
import numpy as np

result = np.sin(np.pi/2)
print(result)
print("\n\n")

#sine values for all of the values in array
aray = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/6])

result = np.sin(aray)

print(result)

1.0



[1.         0.8660254  0.70710678 0.5       ]


# Numpy Products
1. To find the product of the elements in an array, use the prod() function

In [8]:
import numpy as np
aray=np.array([1,2,3,4,5])
p=np.prod(aray)
print(p)

#product of element of 2 Arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
x = np.prod([arr1, arr2])
print("\nproduct of 2 arrays is:")
print(x)


#Product Over an Axis
arr3 = np.array([1, 2, 3, 4])
arr4 = np.array([5, 6, 7, 8])
newarr = np.prod([arr3, arr4], axis=1)
print(newarr)

#commulative product  ::Same as the comulative sum
arr5 = np.array([5, 6, 7, 8])
new= np.cumprod(arr5)

print(new)


120

product of 2 arrays is:
40320
[  24 1680]
[   5   30  210 1680]


# NumPy Differences
1. A discrete difference means subtracting two successive elements.
2. E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]
3. To find the discrete difference, use the diff() function.

In [11]:
import numpy as np
arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr)
print(newarr)

#We can Compute discrete difference of the following array twice:
arr2 = np.array([10, 15, 25, 5])
#for n=1   15-10   25-15  5-25     = [5 10 -20]
#for n=2   10-5    -20-10          =[5 -30]
newarr2 = np.diff(arr2,n=2)
print(newarr2)

[  5  10 -20]
[  5 -30]


# Rounding Decimals
There are primarily five ways of rounding off decimals in NumPy:
1. truncation
2. fix
3. rounding
4. floor
5. ceil

In [18]:
#Truncation
#Remove the decimals, and return the float number closest to zero. Use the trunc() and fix() functions.
import numpy as np
arr = np.trunc([-3.1666, 3.6667])
arr2 = np.fix([-3.1666, 3.6667])
print(arr)
print(arr2)

#The around() function increments preceding digit or decimal by 1 if >=5 else do nothing.
arr3 = np.around(3.1666, 3) #3 indicates that to which decimal place we wanna round off the number
print(arr3)

#The floor() function rounds off decimal to nearest lower integer.
#E.g. floor of 3.166 is 3.
arr4 = np.floor([-3.1666, 3.6667])
print(arr4)

#The ceil() function rounds off decimal to nearest upper integer.
#E.g. ceil of 3.166 is 4.
arr5 = np.ceil([-3.1666, 3.6667])
print(arr5)



[-3.  3.]
[-3.  3.]
3.167
[-4.  3.]
[-3.  4.]


# NumPy Set Operations
1. What is a Set
2. A set in mathematics is a collection of unique elements.
3. Sets are used for operations involving frequent intersection, union and difference operations.

In [23]:
#There is an optional argument assume_unique, in below sets which if set to True can speed up computation.

import numpy as np
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
x = np.unique(arr)
print(x)

#Finding Union
#To find the unique values of two arrays, use the union1d() method.
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.union1d(arr1, arr2)
print(newarr)

# Finding Intersection
#To find only the values that are present in both arrays, use the intersect1d() method.
arr3 = np.array([1, 2, 3, 4])
arr4 = np.array([3, 4, 5, 6])
newarr2= np.intersect1d(arr3, arr4, assume_unique=True)
print(newarr2)


#Finding Difference
#To find only the values in the first set that is NOT present in the seconds set, use the setdiff1d() method.
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])
newarr3 = np.setdiff1d(set1, set2, assume_unique=True)
print(newarr3)


#Finding Symmetric Difference
#To find only the values that are NOT present in BOTH sets, use the setxor1d() method.
set3 = np.array([1, 2, 3, 4])
set4 = np.array([3, 4, 5, 6])
newarr5 = np.setxor1d(set1, set2, assume_unique=True)
print(newarr5)


[1 2 3 4 5 6 7]
[1 2 3 4 5 6]
[3 4]
[1 2]
[1 2 5 6]


# NumPy GCD Greatest Common Denominator
1. Finding GCD (Greatest Common Denominator)
2. The GCD (Greatest Common Denominator), also known as HCF (Highest Common Factor) 
    is the biggest number that is a common factor of both of the numbers.

In [25]:
import numpy as np

num1 = 6
num2 = 9
x = np.gcd(num1, num2)
print(x)
#Returns: 3 because that is the highest number both numbers can be divided by (6/3=2 and 9/3=3).

#To find the Highest Common Factor of all values in an array, you can use the reduce() method.
#The reduce() method will use the ufunc, in this case the gcd() function, on each element, and reduce the array by one dimension.
arr = np.array([20, 8, 32, 36, 16])
x = np.gcd.reduce(arr)
print(x)




3
4


# NumPy Logs
1. NumPy provides functions to perform log at the base 2, e and 10.
2. We will also explore how we can take log for any base by creating a custom ufunc.
3. All of the log functions will place -inf or inf in the elements if the log can not be computed.

In [29]:
#Log at Base 2
#Use the log2() function to perform log at the base 2.

import numpy as np
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(np.log2(arr))
print("\n")
#Log at Base 10
#Use the log10() function to perform log at the base 10.



arr1 = np.arange(1, 10)
print(np.log10(arr1))
print("\n")
#Natural Log, or Log at Base e
#Use the log() function to perform log at the base e.

arr2 = np.arange(1, 10)
print(np.log(arr2))
print("\n")
#Log at Any Base
#NumPy does not provide any function to take log at any base, so we can use the frompyfunc() function 
#along with inbuilt function math.log() with two input parameters and one output parameter:

from math import log
nplog = np.frompyfunc(log, 2, 1)
print(nplog(100, 15))

[      -inf 0.         1.         1.5849625  2.         2.32192809
 2.5849625  2.80735492 3.         3.169925  ]


[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


1.7005483074552052


C:\Users\Hp\AppData\Local\Temp\ipykernel_9604\1860532671.py:6: RuntimeWarning: divide by zero encountered in log2
  print(np.log2(arr))


In [4]:
import numpy as np
     # Original array
arr = np.array([[2,3,4],[5,6,7]])
print('Original array shape:', arr.shape)
# Reshape array
reshaped_arr = arr.reshape(3, -1)
print('Reshaped array shape:', reshaped_arr.shape)



Original array shape: (2, 3)
Reshaped array shape: (3, 2)


In [6]:
import numpy as np
arr1 = np.array([2,3,4])
arr2 = np.array([3,4,5])
arr = np.stack((arr1, arr2), axis=1)
print(arr)


[[2 3]
 [3 4]
 [4 5]]
